1. The MickeyMouse problem

a) Write a program that prints the numbers from 1 to 100. But for multiples of three print Mickey instead of the number and for the multiples of five print Mouse. For numbers which are multiples of both three and five print MickeyMouse

b) Put the result in a tuple and substitute Mickey with Donald and Mouse with Duck

In [1]:
import numpy as np
import pandas as pd
df8 = pd.read_csv(r"C:\\Users\\TEST\\Desktop\\Project Comp physics\\L8",delimiter='\t')
df8

,T,E_avg,Esq_avg,M_avg,Msq_avg,Mabs_avg,X,X_prime,C
0,0.5,-1.840563,220.315450,-0.680200,45.066825,0.744456,0.000000,0.000000,0.000000
1,0.6,-1.999975,255.993800,-0.999994,63.999213,0.999994,0.000021,0.000021,0.000555
2,0.7,-1.999837,255.959700,-0.999959,63.994881,0.999959,0.000116,0.000116,0.002650
3,0.8,-1.999556,255.890025,-0.999888,63.985838,0.999888,0.000296,0.000296,0.005644
4,0.9,-1.998900,255.727350,-0.999722,63.964981,0.999722,0.000640,0.000640,0.010954
5,1.0,-1.996831,255.214825,-0.999194,63.898525,0.999194,0.001683,0.001683,0.025382
6,1.1,-1.994475,254.633900,-0.998584,63.822069,0.998584,0.002855,0.002855,0.038303
7,1.2,-1.988475,253.155750,-0.996984,63.621819,0.996984,0.006031,0.006031,0.067812
8,1.3,-1.979206,250.882225,-0.994494,63.310875,0.994494,0.010565,0.010565,0.105179
9,1.4,-1.967600,248.066250,-0.991228,62.906544,0.991228,0.017442,0.017442,0.149727
10,1.5,-1.950650,243.966050,-0.986397,62.310519,0.986397,0.026584,0.026584,0.197237
11,1.6,-1.930244,239.114925,-0.980309,61.570844,0.980309,0.041519,0.041519,0.258244
12,1.7,-1.900219,232.072975,-0.970381,60.389238,0.970381,0.073113,0.073113,0.339021
13,1.8,-1.857619,222.311675,-0.956163,58.721688,0.956163,0.116609,0.116609,0.451802
14,1.9,-1.818763,213.569900,-0.942706,57.188000,0.942706,0.163955,0.163955,0.516479
15,2.0,-1.747344,198.216475,-0.898066,53.980681,0.912822,1.181641,0.326540,0.702756
16,2.1,-1.684925,185.185050,0.887034,51.250031,0.887072,0.425196,0.423169,0.791570
17,2.2,-1.569556,162.658025,-0.015934,45.518756,0.825447,20.682957,0.868888,1.031733
18,2.3,-1.465944,143.358325,-0.095597,40.295606,0.766991,17.265533,1.150448,1.100736
19,2.4,-1.356106,124.282975,-0.053922,34.524369,0.694391,14.307618,1.527065,1.143304
20,2.5,-1.216506,101.812425,-0.030997,27.184119,0.594678,10.849051,1.820410,1.135940
21,2.6,-1.107525,84.787300,-0.003309,21.738044,0.520059,8.360516,1.703266,0.929609
22,2.7,-1.012894,71.312625,-0.057194,17.264537,0.450694,6.316735,1.579462,0.775252
23,2.8,-0.954638,63.578650,-0.037997,15.272381,0.421791,5.421422,1.387969,0.670071
24,2.9,-0.889281,55.313075,-0.008428,12.417531,0.373453,4.280340,1.204010,0.558921
25,3.0,-0.844475,50.008450,-0.032088,11.018137,0.349619,3.650748,1.065069,0.485291
26,3.1,-0.795531,44.588275,-0.016866,9.468681,0.320116,3.048541,0.938821,0.425036
27,3.2,-0.750756,39.781025,0.014328,8.171306,0.296859,2.549427,0.791023,0.362147
28,3.3,-0.724144,37.050125,0.011050,7.304750,0.276256,2.211193,0.733463,0.320435
29,3.4,-0.692481,34.077375,-0.007019,6.645363,0.264119,1.953591,0.641413,0.293031
30,3.5,-0.663519,31.339075,0.007913,6.021888,0.250469,1.719394,0.573392,0.258173
31,3.6,-0.635613,28.939650,0.009794,5.542075,0.238706,1.537760,0.526476,0.237920
32,3.7,-0.620556,27.640425,-0.009119,5.211288,0.230150,1.407018,0.492235,0.218748
33,3.8,-0.596237,25.665750,0.008025,4.761600,0.220831,1.251968,0.431723,0.201787
34,3.9,-0.578644,24.297525,-0.012691,4.759931,0.220328,1.217852,0.423868,0.188593
35,4.0,-0.559638,22.873900,0.005028,4.304244,0.208447,1.075656,0.380859,0.176842
36,4.1,-0.539356,21.429475,0.001622,4.085381,0.204697,0.996393,0.342373,0.167254
37,4.2,-0.525131,20.337175,0.008541,3.871431,0.198472,0.920658,0.321524,0.152401
38,4.3,-0.516600,19.772050,0.009059,3.738269,0.195122,0.868143,0.302704,0.145593
39,4.4,-0.499431,18.568525,-0.003353,3.546156,0.190391,0.805781,0.278692,0.134551
40,4.5,-0.485444,17.640925,0.005463,3.398900,0.186112,0.754887,0.262684,0.126369
41,4.6,-0.470200,16.775750,-0.009228,3.315481,0.183909,0.719572,0.250181,0.124108
42,4.7,-0.465081,16.407475,0.002772,3.209844,0.179666,0.682841,0.243392,0.116081
43,4.8,-0.447200,15.300450,-0.000850,3.132475,0.178500,0.652589,0.227769,0.108560
44,4.9,-0.437800,14.718650,-0.008334,2.940356,0.171197,0.599165,0.217270,0.102118
45,5.0,-0.428588,14.204650,0.001956,2.826525,0.167894,0.565256,0.204495,0.097947

In [3]:
print(mat[10,31])

1.0

In [4]:
a = np.array([[1,1],[-1,-1]])
b = (((a*255)+255)/2).astype(int)
print(b)

[[255 255]
 [  0   0]]

In [2]:
for i in range(100):
    if (i+1)%3==0 and (i+1)%5==0:
        print("MickeyMouse")
    elif (i+1)%3==0:
        print("Mickey")
    elif (i+1)%5==0:
        print("Mouse")
    else:
        print(str(i+1))

1
2
Mickey
4
Mouse
Mickey
7
8
Mickey
Mouse
11
Mickey
13
14
MickeyMouse
16
17
Mickey
19
Mouse
Mickey
22
23
Mickey
Mouse
26
Mickey
28
29
MickeyMouse
31
32
Mickey
34
Mouse
Mickey
37
38
Mickey
Mouse
41
Mickey
43
44
MickeyMouse
46
47
Mickey
49
Mouse
Mickey
52
53
Mickey
Mouse
56
Mickey
58
59
MickeyMouse
61
62
Mickey
64
Mouse
Mickey
67
68
Mickey
Mouse
71
Mickey
73
74
MickeyMouse
76
77
Mickey
79
Mouse
Mickey
82
83
Mickey
Mouse
86
Mickey
88
89
MickeyMouse
91
92
Mickey
94
Mouse
Mickey
97
98
Mickey
Mouse

In [6]:
cartoonList = []
for i in range(100):
    if (i+1)%3==0 and (i+1)%5==0:
        #print("MickeyMouse")
        cartoonList.append("MickeyMouse")
    elif (i+1)%3==0:
        #print("Mickey")
        cartoonList.append("Mickey")
    elif (i+1)%5==0:
        #print("Mouse")
        cartoonList.append("Mouse")
    else:
        #print(str(i+1))
        cartoonList.append(str(i+1))
MickeyTuple = tuple(cartoonList)
print('\n',MickeyTuple)

for i in range(len(cartoonList)):
    if cartoonList[i]=='Mickey':
        cartoonList[i]="Donald"
    elif cartoonList[i]=="Mouse":
        cartoonList[i]="Duck"
    elif cartoonList[i]=="MickeyMouse":
        cartoonList[i]="DonaldDuck"
print('\n',cartoonList)  
DonaldTuple = tuple(cartoonList) 
print('\n',DonaldTuple)

 ('1', '2', 'Mickey', '4', 'Mouse', 'Mickey', '7', '8', 'Mickey', 'Mouse', '11', 'Mickey', '13', '14', 'MickeyMouse', '16', '17', 'Mickey', '19', 'Mouse', 'Mickey', '22', '23', 'Mickey', 'Mouse', '26', 'Mickey', '28', '29', 'MickeyMouse', '31', '32', 'Mickey', '34', 'Mouse', 'Mickey', '37', '38', 'Mickey', 'Mouse', '41', 'Mickey', '43', '44', 'MickeyMouse', '46', '47', 'Mickey', '49', 'Mouse', 'Mickey', '52', '53', 'Mickey', 'Mouse', '56', 'Mickey', '58', '59', 'MickeyMouse', '61', '62', 'Mickey', '64', 'Mouse', 'Mickey', '67', '68', 'Mickey', 'Mouse', '71', 'Mickey', '73', '74', 'MickeyMouse', '76', '77', 'Mickey', '79', 'Mouse', 'Mickey', '82', '83', 'Mickey', 'Mouse', '86', 'Mickey', '88', '89', 'MickeyMouse', '91', '92', 'Mickey', '94', 'Mouse', 'Mickey', '97', '98', 'Mickey', 'Mouse')

 ['1', '2', 'Donald', '4', 'Duck', 'Donald', '7', '8', 'Donald', 'Duck', '11', 'Donald', '13', '14', 'DonaldDuck', '16', '17', 'Donald', '19', 'Duck', 'Donald', '22', '23', 'Donald', 'Duck', '26', 'Donald', '28', '29', 'DonaldDuck', '31', '32', 'Donald', '34', 'Duck', 'Donald', '37', '38', 'Donald', 'Duck', '41', 'Donald', '43', '44', 'DonaldDuck', '46', '47', 'Donald', '49', 'Duck', 'Donald', '52', '53', 'Donald', 'Duck', '56', 'Donald', '58', '59', 'DonaldDuck', '61', '62', 'Donald', '64', 'Duck', 'Donald', '67', '68', 'Donald', 'Duck', '71', 'Donald', '73', '74', 'DonaldDuck', '76', '77', 'Donald', '79', 'Duck', 'Donald', '82', '83', 'Donald', 'Duck', '86', 'Donald', '88', '89', 'DonaldDuck', '91', '92', 'Donald', '94', 'Duck', 'Donald', '97', '98', 'Donald', 'Duck']

 ('1', '2', 'Donald', '4', 'Duck', 'Donald', '7', '8', 'Donald', 'Duck', '11', 'Donald', '13', '14', 'DonaldDuck', '16', '17', 'Donald', '19', 'Duck', 'Donald', '22', '23', 'Donald', 'Duck', '26', 'Donald', '28', '29', 'DonaldDuck', '31', '32', 'Donald', '34', 'Duck', 'Donald', '37', '38', 'Donald', 'Duck', '41', 'Donald', '43', '44', 'DonaldDuck', '46', '47', 'Donald', '49', 'Duck', 'Donald', '52', '53', 'Donald', 'Duck', '56', 'Donald', '58', '59', 'DonaldDuck', '61', '62', 'Donald', '64', 'Duck', 'Donald', '67', '68', 'Donald', 'Duck', '71', 'Donald', '73', '74', 'DonaldDuck', '76', '77', 'Donald', '79', 'Duck', 'Donald', '82', '83', 'Donald', 'Duck', '86', 'Donald', '88', '89', 'DonaldDuck', '91', '92', 'Donald', '94', 'Duck', 'Donald', '97', '98', 'Donald', 'Duck')

2\. The swap function

Write a function that swap the values of two input variables x and y (whatever the type). Try to do that also without a temporary variable

In [7]:
def swap1(x,y):
    temp = x
    x = y
    y = temp
    return(x,y)

def swap2(x,y):
    temp = [x,y]
    temp.reverse()
    return(temp[0],temp[1])

def swap3(x,y):
    return(y,x)

swap1(2,3)
swap2("demon","God")
swap3("God","Goddess")

('Goddess', 'God')

3\. Computing the distance

Write a function that calculates and returns the euclidean distance between two points *u* and *v*, where *u* and *v* are both 2-tuples *(x,y)*. For example, if *u=(3,0)* and *v=(0,4)*, the function should return 5

In [8]:
from math import sqrt 
u = (3,0)
v = (0,4)

def dist(u,v):
    x1=u[0]
    x2=v[0]
    y1=u[1]
    y2=v[1]
    length = sqrt((x1-x2)**2+(y1-y2)**2)
    return(length)
dist(u,v)

5.0

4\. Counting letters

Write a program to calculate the number of times each character occurs in a given string *s*. Ignore differneces in capitalization

In [9]:
from collections import Counter
string = "I love Laboratory of Computational Physics"
count = Counter(string.lower())
print(count)

Counter({'o': 6, ' ': 5, 'a': 4, 'i': 3, 'l': 3, 't': 3, 'r': 2, 'y': 2, 'c': 2, 'p': 2, 's': 2, 'v': 1, 'e': 1, 'b': 1, 'f': 1, 'm': 1, 'u': 1, 'n': 1, 'h': 1})

5\. Isolating the unique

Write a function that determines and count the unique numbers in the list *l*

In [10]:
l = [36, 45, 58, 3, 74, 96, 64, 45, 31, 10, 24, 19, 33, 86, 99, 18, 63, 70, 85,
 85, 63, 47, 56, 42, 70, 84, 88, 55, 20, 54, 8, 56, 51, 79, 81, 57, 37, 91,
 1, 84, 84, 36, 66, 9, 89, 50, 42, 91, 50, 95, 90, 98, 39, 16, 82, 31, 92, 41,
 45, 30, 66, 70, 34, 85, 94, 5, 3, 36, 72, 91, 84, 34, 87, 75, 53, 51, 20, 89, 51, 20]

from collections import Counter
count = Counter(l)
count = dict(count)#count represents dictionary. Converting formally into a dictionary.
#print(count)
#print(count.items())

uniqueList=[]
for key,value in count.items():
     if value==1:
            uniqueList.append(key)
print("List of Unique numbers: ",uniqueList)
print("Length of Unique list: ",len(uniqueList))

List of Unique numbers:  [58, 74, 96, 64, 10, 24, 19, 33, 86, 99, 18, 47, 88, 55, 54, 8, 79, 81, 57, 37, 1, 9, 95, 90, 98, 39, 16, 82, 92, 41, 30, 94, 5, 72, 87, 75, 53]
Length of Unique list:  37

6\. Combination of functions

Write two functions - one that returns the square of a number, and one that returns the cube. Now write a third function that returns the number raised to the 6th power using the two previous functions.

In [11]:
def square(x):
    return(x**2)

def cube(x):
    return(x**3)

def powerSix(x):
    return(square(cube(x)))
powerSix(2)

64

7\. Cubes

Create a list of the cubes of x for x in *[0, 10]* using:

a) a for loop

b) a list comprehension

In [12]:
x=range(11)
cubeX1 = []
for element in x:
    cubeX1.append(element**3)
print(cubeX1)

cubeX2 = [element**3 for element in x]#list comprehension
print(cubeX2)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

8\. Nested list comprehension

A Pythagorean triple is an integer solution to the Pythagorean theorem $a^2+b^2=c^2$. The first Pythagorean triple is (3,4,5). Find and put in a tuple all unique Pythagorean triples for the positive integers a, b and c less than 100.

In [13]:
"""
PythogoreanTriplets = []
for a in range(1,100):
    for b in range(1,100):
        for c in range(1,100):
            if a**2 + b**2 == c**2:
                PythogoreanTriplets.append((a,b,c))
print(PythogoreanTriplets)
"""
#Just go on writing for loops instruction like above without ":" symbol. 
PythogoreanTriplets = [(a,b,c)for a in range(1,100) for b in range(1,100) for c in range(1,100) if a**2+b**2==c**2]
print(PythogoreanTriplets)

[(3, 4, 5), (4, 3, 5), (5, 12, 13), (6, 8, 10), (7, 24, 25), (8, 6, 10), (8, 15, 17), (9, 12, 15), (9, 40, 41), (10, 24, 26), (11, 60, 61), (12, 5, 13), (12, 9, 15), (12, 16, 20), (12, 35, 37), (13, 84, 85), (14, 48, 50), (15, 8, 17), (15, 20, 25), (15, 36, 39), (16, 12, 20), (16, 30, 34), (16, 63, 65), (18, 24, 30), (18, 80, 82), (20, 15, 25), (20, 21, 29), (20, 48, 52), (21, 20, 29), (21, 28, 35), (21, 72, 75), (24, 7, 25), (24, 10, 26), (24, 18, 30), (24, 32, 40), (24, 45, 51), (24, 70, 74), (25, 60, 65), (27, 36, 45), (28, 21, 35), (28, 45, 53), (30, 16, 34), (30, 40, 50), (30, 72, 78), (32, 24, 40), (32, 60, 68), (33, 44, 55), (33, 56, 65), (35, 12, 37), (35, 84, 91), (36, 15, 39), (36, 27, 45), (36, 48, 60), (36, 77, 85), (39, 52, 65), (39, 80, 89), (40, 9, 41), (40, 30, 50), (40, 42, 58), (40, 75, 85), (42, 40, 58), (42, 56, 70), (44, 33, 55), (45, 24, 51), (45, 28, 53), (45, 60, 75), (48, 14, 50), (48, 20, 52), (48, 36, 60), (48, 55, 73), (48, 64, 80), (51, 68, 85), (52, 39, 65), (54, 72, 90), (55, 48, 73), (56, 33, 65), (56, 42, 70), (57, 76, 95), (60, 11, 61), (60, 25, 65), (60, 32, 68), (60, 45, 75), (60, 63, 87), (63, 16, 65), (63, 60, 87), (64, 48, 80), (65, 72, 97), (68, 51, 85), (70, 24, 74), (72, 21, 75), (72, 30, 78), (72, 54, 90), (72, 65, 97), (75, 40, 85), (76, 57, 95), (77, 36, 85), (80, 18, 82), (80, 39, 89), (84, 13, 85), (84, 35, 91)]

9\. Normalization

Write a function that takes a tuple of numbers and returns it with the entries normalized to one

In [14]:
NumberTuple = (1,2,1)

def normalize(tup):
    squares = [x**2 for x in tup]
    sumSquares = sum(squares)
    normList = [elem/(sumSquares**0.5) for elem in NumberTuple]
    return tuple(normList)

normalize(NumberTuple)

(0.4082482904638631, 0.8164965809277261, 0.4082482904638631)